name: Run Terraform AWS

on:
  push:
    branches: [ "master", "main" ]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build, tag, and push docker image to Amazon ECR Public
      - name: Build, tag, and push docker image to Amazon ECR Public
        id: build-and-push
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          IMAGE_URI=public.ecr.aws/r6m3r1y7/fundagold_repository:${IMAGE_TAG}
  
          docker build --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}
          echo "::set-output name=image_uri::${IMAGE_URI}"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_image_uri: ${{ IMAGE_URI }}
